language: c
env:
  global:
    - GAPROOT=gaproot
    - COVDIR=coverage
    - GAP_PKGS_TO_BUILD="anupq io profiling"

addons:
  apt_packages:
    - libgmp-dev
    - libreadline-dev
    - libgmp-dev:i386
    - libreadline-dev:i386
    - gcc-multilib
    - g++-multilib

matrix:
  include:
    - env: CFLAGS="-O2" CC=clang CXX=clang++
      compiler: clang
    - env: CFLAGS="-O2"
      compiler: gcc
    - env: ABI=32

branches:
  only:
    - master

before_script:
  - export GAPROOT="$HOME/gap"
  - scripts/build_gap.sh

# Create directory to collect coverage data.
# Start two SCSCP servers, collect coverage from the one running
# on the default port (it is exercised by more tests).
# Sleep to allow servers to be up and running, then run tests.
script:
  - scripts/build_pkg.sh
  - mkdir ${COVDIR}
  - GAPROOT=${GAPROOT} GAPOPTS="-l $PWD/${GAPROOT}; --cover ${COVDIR}/test-server.coverage" ./gapd.sh -p 26133
  - GAPROOT=${GAPROOT} GAPOPTS="-l $PWD/${GAPROOT};" ./gapd.sh -p 26134
  - sleep 30
  - scripts/run_tests.sh
after_script:
  - ls ${COVDIR}
  - bash scripts/gather-coverage.sh
  - bash <(curl -s https://codecov.io/bash)
